Namespace SQL.View
    Public Class Common
        Public Sub New()
            ' Just so a compiler doesnt create a default constructor
        End Sub
        Public Shared Function RACE_XML_RACE_EXTENDED(MeetingOADate As String, MeetingNumber As String, Connection As Utils.Connection) As Data.DataTable
            Dim CMDTEXT As String = "SELECT RACE_XML.NUMBER, RACE_XML.LENGTH, RACE_XML.NAME, RACE_XML.START_TIME, RACE_XML.VENUE_ID, RACE_XML.RUNNERSINRACE, RACE_EXTENDED.HASMODEL 
            FROM RACE_XML LEFT OUTER JOIN RACE_EXTENDED ON RACE_XML.MEETING_XML_OADATE = RACE_EXTENDED.MEETING_XML_OADATE AND RACE_XML.MEETING_XML_NUMBER = RACE_EXTENDED.MEETING_XML_NUMBER AND RACE_XML.NUMBER = RACE_EXTENDED.NUMBER 
            WHERE (RACE_XML.MEETING_XML_NUMBER = " & MeetingNumber & ") AND (RACE_XML.MEETING_XML_OADATE = " & MeetingOADate & ") 
            ORDER BY RACE_XML.NUMBER ASC "

            Return Connection.GetDataTable(CMDTEXT)
        End Function
        Public Shared Function RunnerRaceList(CountryID As String, MeetingOADate As String, MeetingType As String, EntryName As String, Connection As Utils.Connection) As Data.DataTable
            Dim CMDTEXT As String = "SELECT RACE_XML.MEETING_XML_OADATE, RACE_XML.MEETING_XML_NUMBER, RACE_XML.NUMBER AS RACE_XML_NUMBER, RACE_XML.LENGTH, RACE_XML.NAME, RACE_XML.START_TIME, RACE_XML.VENUE_ID, VENUES.NAME AS VENUE_NAME, RACE_XML.RUNNERSINRACE, MEETING_XML.TYPE, MEETING_XML.COUNTRY_ID, RESULTS_EXTENDED.FINISH_POSITION, RESULTS_EXTENDED.DISTANCE_BEHIND, RESULTS_EXTENDED.EXCEPTION, ENTRY_XML.SCRATCHED, ENTRY_XML.BARRIER  
            FROM RESULTS_EXTENDED RIGHT OUTER JOIN ENTRY_XML ON RESULTS_EXTENDED.MEETING_XML_OADATE = ENTRY_XML.MEETING_XML_OADATE AND RESULTS_EXTENDED.MEETING_XML_NUMBER = ENTRY_XML.MEETING_XML_NUMBER AND RESULTS_EXTENDED.RACE_XML_NUMBER = ENTRY_XML.RACE_XML_NUMBER AND RESULTS_EXTENDED.NUMBER = ENTRY_XML.NUMBER RIGHT OUTER JOIN RACE_XML INNER JOIN VENUES ON RACE_XML.VENUE_ID = VENUES.VENUE_ID INNER JOIN MEETING_XML ON RACE_XML.MEETING_XML_OADATE = MEETING_XML.OADATE AND RACE_XML.MEETING_XML_NUMBER = MEETING_XML.NUMBER ON ENTRY_XML.MEETING_XML_OADATE = RACE_XML.MEETING_XML_OADATE AND ENTRY_XML.MEETING_XML_NUMBER = RACE_XML.MEETING_XML_NUMBER AND ENTRY_XML.RACE_XML_NUMBER = RACE_XML.NUMBER 
            WHERE (MEETING_XML.TYPE = N'" & MeetingType & "') AND (MEETING_XML.COUNTRY_ID = " & CountryID & ") AND (ENTRY_XML.NAME = N'" & Replace(EntryName, "'", "' + CHAR(39) + '") & "') AND (RACE_XML.MEETING_XML_OADATE < " & MeetingOADate & ") 
            ORDER BY RACE_XML.MEETING_XML_OADATE DESC, RACE_XML.MEETING_XML_NUMBER DESC, RACE_XML_NUMBER"

            Return Connection.GetDataTable(CMDTEXT)
        End Function
    End Class
End Namespace