Namespace SQL
    Friend NotInheritable Class Statistics
        Private Sub New()
            ' Just so the compiler doesnt create a default constructor
        End Sub
        Friend Shared Function GetRunnerDataTable(OADate As String, CountryID As String, [Type] As String, Name As String, Connection As Utils.Connection) As Data.DataTable
            Dim CommandText As String = "SELECT RACE_XML.LENGTH, ENTRY_XML.SCRATCHED, RESULTS_XML_PLACINGS.FINISH_POSITION, RESULTS_XML_PLACINGS.DISTANCE_BEHIND, RESULTS_XML_ALSORAN.FINISH_POSITION AS ALSORAN_FINISHPOSITION, RESULTS_XML_ALSORAN.DISTANCE_BEHIND AS ALSORAN_DISTANCEBEHIND, RESULTS_XML_ALSORAN.EXCEPTION, ENTRY_XML.MEETING_XML_OADATE, RACE_XML.RUNNERSINRACE  
                FROM  RESULTS_XML_ALSORAN RIGHT OUTER JOIN ENTRY_XML ON RESULTS_XML_ALSORAN.MEETING_XML_OADATE = ENTRY_XML.MEETING_XML_OADATE AND RESULTS_XML_ALSORAN.MEETING_XML_NUMBER = ENTRY_XML.MEETING_XML_NUMBER AND RESULTS_XML_ALSORAN.RACE_XML_NUMBER = ENTRY_XML.RACE_XML_NUMBER AND RESULTS_XML_ALSORAN.NUMBER = ENTRY_XML.NUMBER RIGHT OUTER JOIN MEETING_XML INNER JOIN RACE_XML ON MEETING_XML.OADATE = RACE_XML.MEETING_XML_OADATE AND MEETING_XML.NUMBER = RACE_XML.MEETING_XML_NUMBER ON ENTRY_XML.MEETING_XML_OADATE = RACE_XML.MEETING_XML_OADATE AND ENTRY_XML.MEETING_XML_NUMBER = RACE_XML.MEETING_XML_NUMBER AND ENTRY_XML.RACE_XML_NUMBER = RACE_XML.NUMBER LEFT OUTER JOIN RESULTS_XML_PLACINGS ON ENTRY_XML.MEETING_XML_OADATE = RESULTS_XML_PLACINGS.MEETING_XML_OADATE AND ENTRY_XML.MEETING_XML_NUMBER = RESULTS_XML_PLACINGS.MEETING_XML_NUMBER AND ENTRY_XML.RACE_XML_NUMBER = RESULTS_XML_PLACINGS.RACE_XML_NUMBER AND ENTRY_XML.NUMBER = RESULTS_XML_PLACINGS.NUMBER 
                WHERE (MEETING_XML.COUNTRY_ID=" & CountryID & ") AND (MEETING_XML.TYPE = N'" & [Type] & "') AND (ENTRY_XML.NAME = N'" & Replace(Name, "'", "' + CHAR(39) +'") & "') AND ((ENTRY_XML.MEETING_XML_OADATE < " & OADate & ") AND (ENTRY_XML.MEETING_XML_OADATE > " & (CInt(OADate) - 365).ToString & ")) 
                ORDER BY ENTRY_XML.MEETING_XML_OADATE DESC"

            Return Connection.GetDataTable(CommandText)
        End Function
    End Class
End Namespace