Namespace DataTables
    Public Class StatsLastX
        Private Sub New()
            ' Just so the compiler doesnt create a default constructor
        End Sub
        Public Shared Function Last10DataTable(OADate As String, MeetingNumber As String, RaceNumber As String, Connection As Utils.Connection) As Data.DataTable
            Dim CMDTEXT As String = "SELECT ENTRY_XML.MEETING_XML_OADATE, ENTRY_XML.MEETING_XML_NUMBER, ENTRY_XML.RACE_XML_NUMBER, ENTRY_XML.NUMBER, ENTRY_XML.BARRIER, STATS_RACE_BARRIER.RANK AS BARRIER_RANK, ENTRY_XML.NAME, ENTRY_XML.SCRATCHED, STATS_ENTRY_LAST10RUNS.*
                FROM  ENTRY_XML LEFT OUTER JOIN STATS_RACE_BARRIER ON ENTRY_XML.MEETING_XML_OADATE = STATS_RACE_BARRIER.MEETING_XML_OADATE AND ENTRY_XML.MEETING_XML_NUMBER = STATS_RACE_BARRIER.MEETING_XML_NUMBER AND ENTRY_XML.RACE_XML_NUMBER = STATS_RACE_BARRIER.RACE_XML_NUMBER AND ENTRY_XML.NUMBER = STATS_RACE_BARRIER.BARRIER LEFT OUTER JOIN STATS_ENTRY_LAST10RUNS ON ENTRY_XML.MEETING_XML_OADATE = STATS_ENTRY_LAST10RUNS.MEETING_XML_OADATE AND ENTRY_XML.MEETING_XML_NUMBER = STATS_ENTRY_LAST10RUNS.MEETING_XML_NUMBER AND ENTRY_XML.RACE_XML_NUMBER = STATS_ENTRY_LAST10RUNS.RACE_XML_NUMBER AND ENTRY_XML.NUMBER = STATS_ENTRY_LAST10RUNS.NUMBER 
                WHERE (ENTRY_XML.MEETING_XML_OADATE = " & OADate & ") AND (ENTRY_XML.RACE_XML_NUMBER = " & RaceNumber & ") AND (ENTRY_XML.MEETING_XML_NUMBER = " & MeetingNumber & ")"

            Return Connection.GetDataTable(CMDTEXT)
        End Function
        Public Shared Function VenueLast10DataTable(OADate As String, MeetingNumber As String, RaceNumber As String, Connection As Utils.Connection) As Data.DataTable
            Dim CMDTEXT As String = "SELECT ENTRY_XML.MEETING_XML_OADATE, ENTRY_XML.MEETING_XML_NUMBER, ENTRY_XML.RACE_XML_NUMBER, ENTRY_XML.NUMBER, ENTRY_XML.BARRIER, STATS_RACE_BARRIER.RANK AS BARRIER_RANK, ENTRY_XML.NAME, ENTRY_XML.SCRATCHED, STATS_ENTRY_VENUE_LAST10RUNS.*
                FROM  ENTRY_XML LEFT OUTER JOIN STATS_RACE_BARRIER ON ENTRY_XML.MEETING_XML_OADATE = STATS_RACE_BARRIER.MEETING_XML_OADATE AND ENTRY_XML.MEETING_XML_NUMBER = STATS_RACE_BARRIER.MEETING_XML_NUMBER AND ENTRY_XML.RACE_XML_NUMBER = STATS_RACE_BARRIER.RACE_XML_NUMBER AND ENTRY_XML.NUMBER = STATS_RACE_BARRIER.BARRIER LEFT OUTER JOIN STATS_ENTRY_VENUE_LAST10RUNS ON ENTRY_XML.MEETING_XML_OADATE = STATS_ENTRY_VENUE_LAST10RUNS.MEETING_XML_OADATE AND ENTRY_XML.MEETING_XML_NUMBER = STATS_ENTRY_VENUE_LAST10RUNS.MEETING_XML_NUMBER AND ENTRY_XML.RACE_XML_NUMBER = STATS_ENTRY_VENUE_LAST10RUNS.RACE_XML_NUMBER AND ENTRY_XML.NUMBER = STATS_ENTRY_VENUE_LAST10RUNS.NUMBER 
                WHERE (ENTRY_XML.MEETING_XML_OADATE = " & OADate & ") AND (ENTRY_XML.RACE_XML_NUMBER = " & RaceNumber & ") AND (ENTRY_XML.MEETING_XML_NUMBER = " & MeetingNumber & ")"

            Return Connection.GetDataTable(CMDTEXT)
        End Function
        Public Shared Function Last3DataTable(OADate As String, MeetingNumber As String, RaceNumber As String, Connection As Utils.Connection) As Data.DataTable
            Dim CMDTEXT As String = "SELECT ENTRY_XML.MEETING_XML_OADATE, ENTRY_XML.MEETING_XML_NUMBER, ENTRY_XML.RACE_XML_NUMBER, ENTRY_XML.NUMBER, ENTRY_XML.BARRIER, STATS_RACE_BARRIER.RANK AS BARRIER_RANK, ENTRY_XML.NAME, ENTRY_XML.SCRATCHED, STATS_ENTRY_LAST3RUNS.*
                FROM  ENTRY_XML LEFT OUTER JOIN STATS_RACE_BARRIER ON ENTRY_XML.MEETING_XML_OADATE = STATS_RACE_BARRIER.MEETING_XML_OADATE AND ENTRY_XML.MEETING_XML_NUMBER = STATS_RACE_BARRIER.MEETING_XML_NUMBER AND ENTRY_XML.RACE_XML_NUMBER = STATS_RACE_BARRIER.RACE_XML_NUMBER AND ENTRY_XML.NUMBER = STATS_RACE_BARRIER.BARRIER LEFT OUTER JOIN STATS_ENTRY_LAST3RUNS ON ENTRY_XML.MEETING_XML_OADATE = STATS_ENTRY_LAST3RUNS.MEETING_XML_OADATE AND ENTRY_XML.MEETING_XML_NUMBER = STATS_ENTRY_LAST3RUNS.MEETING_XML_NUMBER AND ENTRY_XML.RACE_XML_NUMBER = STATS_ENTRY_LAST3RUNS.RACE_XML_NUMBER AND ENTRY_XML.NUMBER = STATS_ENTRY_LAST3RUNS.NUMBER 
                WHERE (ENTRY_XML.MEETING_XML_OADATE = " & OADate & ") AND (ENTRY_XML.RACE_XML_NUMBER = " & RaceNumber & ") AND (ENTRY_XML.MEETING_XML_NUMBER = " & MeetingNumber & ")"

            Return Connection.GetDataTable(CMDTEXT)
        End Function
        Public Shared Function VenueLast3DataTable(OADate As String, MeetingNumber As String, RaceNumber As String, Connection As Utils.Connection) As Data.DataTable
            Dim CMDTEXT As String = "SELECT ENTRY_XML.MEETING_XML_OADATE, ENTRY_XML.MEETING_XML_NUMBER, ENTRY_XML.RACE_XML_NUMBER, ENTRY_XML.NUMBER, ENTRY_XML.BARRIER, STATS_RACE_BARRIER.RANK AS BARRIER_RANK, ENTRY_XML.NAME, ENTRY_XML.SCRATCHED, STATS_ENTRY_VENUE_LAST3RUNS.*
                FROM  ENTRY_XML LEFT OUTER JOIN STATS_RACE_BARRIER ON ENTRY_XML.MEETING_XML_OADATE = STATS_RACE_BARRIER.MEETING_XML_OADATE AND ENTRY_XML.MEETING_XML_NUMBER = STATS_RACE_BARRIER.MEETING_XML_NUMBER AND ENTRY_XML.RACE_XML_NUMBER = STATS_RACE_BARRIER.RACE_XML_NUMBER AND ENTRY_XML.NUMBER = STATS_RACE_BARRIER.BARRIER LEFT OUTER JOIN STATS_ENTRY_LAST3RUNS ON ENTRY_XML.MEETING_XML_OADATE = STATS_ENTRY_VENUE_LAST3RUNS.MEETING_XML_OADATE AND ENTRY_XML.MEETING_XML_NUMBER = STATS_ENTRY_VENUE_LAST3RUNS.MEETING_XML_NUMBER AND ENTRY_XML.RACE_XML_NUMBER = STATS_ENTRY_VENUE_LAST3RUNS.RACE_XML_NUMBER AND ENTRY_XML.NUMBER = STATS_ENTRY_VENUE_LAST3RUNS.NUMBER 
                WHERE (ENTRY_XML.MEETING_XML_OADATE = " & OADate & ") AND (ENTRY_XML.RACE_XML_NUMBER = " & RaceNumber & ") AND (ENTRY_XML.MEETING_XML_NUMBER = " & MeetingNumber & ")"

            Return Connection.GetDataTable(CMDTEXT)
        End Function
    End Class
End Namespace